---
- name: Copy kubeadm-config.yaml to master
  template:
    src: kubeadm-config.yaml
    dest: /tmp/kubeadm-config.yaml

- name: Run kubeadm init
  command: kubeadm init --config=/tmp/kubeadm-config.yaml
