apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: {{ kubernetes_version }}
imageRepository: k8s.gcr.io
networking:
  podSubnet: {{ pod_network_cidr }}
controlPlaneEndpoint: {{ apiserver_endpoint }}
