---
- hosts: k8s_masters[0]
  become: yes
  tasks:
    - name: Generate kubeadm join command
      shell: kubeadm token create --print-join-command
      register: kubeadm_join_cmd

- hosts: k8s_workers
  become: yes
  serial: 1
  tasks:
    - name: Run kubeadm join
      shell: "{{ hostvars[groups['k8s_masters'][0]].kubeadm_join_cmd.stdout }}"
